name: mail2tg-hourly

on:
  schedule:
    - cron: "0 * * * *" # 每小时00分（UTC）
  workflow_dispatch: {}

jobs:
  run-mail2tg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Actions 环境：一次性执行 + 禁用 state
      DISABLE_STATE: "1"
      POLL_SECONDS: "0"

      # Telegram
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      # 邮箱（用哪个就配哪个）
      GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
      QQ_EMAIL_AUTH_CODE: ${{ secrets.QQ_EMAIL_AUTH_CODE }}

      # 过滤
      SENDER_DOMAINS: amazon.com
      WINDOW_HOURS: "1"
      UNREAD_ONLY: "1"

      # 可选：OpenAI 摘要
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true

      - name: Build
        run: |
          go mod tidy
          go build -o mail2tg .

      - name: Run one-shot
        run: ./mail2tg
